[package]
name = "rust-kiam_upload_to_s3"
version = "0.1.0"
authors = ["Emil H. Clausen <emcla@dfds.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_core = "0.40.0"
rusoto_s3 = "0.40.0"