apiVersion: batch/v1
kind: Job
metadata:
  labels:
    name: kiam-nodejs
  name: kiam-nodejs
spec:
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::090185641622:role/s3_kiam_test
      labels:
        name: kiam-nodejs
    spec:
      containers:
      - image: 090185641622.dkr.ecr.eu-central-1.amazonaws.com/emcla/kiam-nodejs:latest
        imagePullPolicy: Always
        name: kiam-nodejs
      restartPolicy: Never
